### ISSUE TITLE
Recipe Chain Error

### ISSUE THREAD

**Issue by coingroup** [amzn/fire-app-builder#20]
I'm new to this but I've been able to follow the docs thus far. I'm getting two errors on my app and I'm stumped. Any help is greatly appreciated:

`E/com.amazon.android.tv.tenfoot.ui.activities.SplashActivity: Service is unavailable. Please try again later.`

`E/ContentBrowser: Recipe chain failed:
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amazon.android.model.content.ContentContainer.getName()' on a null object reference
                      at com.amazon.android.contentbrowser.ContentLoader.lambda$getCategoriesObservable$2(ContentLoader.java:196)
                      at com.amazon.android.contentbrowser.ContentLoader$$Lambda$3.call(Unknown Source)
                      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                      at rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
                      at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
                      at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:199)
                      at com.amazon.dynamicparser.DynamicParser$1.onRecipeCooked(DynamicParser.java:346)
                      at com.amazon.dynamicparser.DynamicParser.translateMapsToObjects(DynamicParser.java:613)
                      at com.amazon.dynamicparser.DynamicParser.lambda$cookRecipeObservable$0(DynamicParser.java:334)
                      at com.amazon.dynamicparser.DynamicParser$$Lambda$1.call(Unknown Source)
                      at rx.Observable.unsafeSubscribe(Observable.java:8098)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
                      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule$1.onRecipeCooked(DataLoaderModule.java:88)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule$3.onSuccess(DataLoaderModule.java:391)
                      at com.amazon.dataloader.datadownloader.ADataDownloader.loadData(ADataDownloader.java:52)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.loadDataFromSource(DataLoaderModule.java:433)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.access$500(DataLoaderModule.java:44)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule$2.onSuccess(DataLoaderModule.java:324)
                      at com.amazon.dataloader.cacheManager.CacheManagerAdapter.loadData(CacheManagerAdapter.java:115)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.loadDataFromCache(DataLoaderModule.java:417)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.access$600(DataLoaderModule.java:44)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule$LoadDataTask.loadData(DataLoaderModule.java:251)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.cookRecipe(DataLoaderModule.java:140)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule.lambda$cookRecipeObservable$0(DataLoaderModule.java:73)
                      at com.amazon.dataloader.dataloadmanager.DataLoaderModule$$Lambda$1.call(Unknown Source)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable$2.call(Observable.java:162)
                      at rx.Observable$2.call(Observable.java:154)
                      at rx.Observable.unsafeSubscribe(Observable.java:8098)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
                      at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
                      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                      at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
                  	at rx.internal.operators.OnSub`

**Comment by brian-ross** [comment]
Can you please check that your content recipe's match list is set up properly? The items in the match list should map to the items in the feed. For example, follow the sample feed and the same match list of the content recipe.
