### ISSUE TITLE
VAST Ads with min/max bitrate cause error

### ISSUE THREAD

**Issue by traviskroberts** [amzn/fire-app-builder#45]
If the XML response for a Vast ad contains a `MediaFile` element that has `minBitrate` and `maxBitrate` (ex: HLS) as opposed to just `bitrate`, it causes an error in [MediaFile.java:134](https://github.com/amzn/fire-app-builder/blob/f63b1622449c60587bd97b13038a40e00d9b38e2/VastAdsComponent/src/main/java/com/amazon/android/ads/vast/model/vast/MediaFile.java#L134).

Example of working `MediaFile` element:

```xml
<MediaFile id="GDFP" delivery="progressive" width="320" height="180" type="video/3gpp" bitrate="237" scalable="true" maintainAspectRatio="true">
  <![CDATA[MEDIA_URL]]>
</MediaFile>
```

Example of `MediaFile` element that causes an error:

```xml
<MediaFile id="GDFP" delivery="streaming" width="1280" height="720" type="application/x-mpegURL" minBitrate="45" maxBitrate="1775" scalable="true" maintainAspectRatio="true">
  <![CDATA[MEDIA_URL]]>
</MediaFile>
```

Full stacktrace:

```java
E/AdTagProcessor: Caught IllegalArgumentException.
  java.lang.NumberFormatException: Invalid long: "null"
    at java.lang.Long.invalidLong(Long.java:124)
    at java.lang.Long.parseLong(Long.java:345)
    at java.lang.Long.parseLong(Long.java:321)
    at java.lang.Long.valueOf(Long.java:511)
    at com.amazon.android.ads.vast.model.vast.MediaFile.<init>(MediaFile.java:134)
    at com.amazon.android.ads.vast.model.vast.LinearAd.<init>(LinearAd.java:80)
    at com.amazon.android.ads.vast.model.vast.Creative.<init>(Creative.java:81)
    at com.amazon.android.ads.vast.model.vast.Inline.<init>(Inline.java:77)
    at com.amazon.android.ads.vast.model.vast.AdElement.createInstance(AdElement.java:97)
    at com.amazon.android.ads.vast.model.vast.VastResponse.createInstance(VastResponse.java:125)
    at com.amazon.android.ads.vast.processor.AdTagProcessor.process(AdTagProcessor.java:122)
    at com.amazon.android.ads.vast.VASTAdsPlayer$2.run(VASTAdsPlayer.java:578)
    at java.lang.Thread.run(Thread.java:818)
```

Fire App Builder Version: 1.0.7

Let me know if you need any additional information.

**Comment by traviskroberts** [comment]
I've gotten around this temporarily by creating an ad delivery campaign that does not include any "streaming" video formats (like HLS or DASH).

**Comment by nbcartier4292** [comment]
@levonlevonian  I'm facing a similar issue - I'm trying to insert a third party VAST tag with the VAST Ad Component on a HLS stream. Can you point me to the fixed issue? Thanks!
