### ISSUE TITLE
VAST Ad Component - Error with HLS Streams

### ISSUE THREAD

**Issue by nbcartier4292** [amzn/fire-app-builder#64]
Hello,

I can't seem to figure out how to get a VAST tag to serve an ad with the Google IMA SDK. I keep getting this error:

E/AdTagProcessor: Could not get data from url http://s.vertamedia.com/?width=1920&height=1080&cb=%%CACHEBUSTER%%&ua=%%USER_AGENT%%&uip=%%USER_IP%%&app_name=AnthymTV&app_bundle=B089J9QYM8&device_model=Fire%20TV&device_make=Fire%20TV&device_category=ctv&app_store_url=https%3A%2F%2Fwww.amazon.com%2FAnthymTV%2Fdp%2FB089J9QYM8&device_id=%%ADVERTISING_IDENTIFIER_PLAIN%%&vast_version=2&aid=551574&ad_duration=30&device_os=Fire%20OS&device_osv=Fire%20OS%207&dnt=%%ADVERTISING_IDENTIFIER_IS_LAT%%&gdpr=0&gdpr_consent=&video_title=%%VIDEO_TITLE%%&video_id=%%VIDEO_ID%%&video_duration=%%VIDEO_DURATION_SEC%%&us_privacy=1YNN&correlator=1597938893519
    java.io.IOException: Invalid % sequence: %%C in query at index 51: http://s.vertamedia.com/?width=1920&height=1080&cb=%%CACHEBUSTER%%&ua=%%USER_AGENT%%&uip=%%USER_IP%%&app_name=AnthymTV&app_bundle=B089J9QYM8&device_model=Fire%20TV&device_make=Fire%20TV&device_category=ctv&app_store_url=https%3A%2F%2Fwww.amazon.com%2FAnthymTV%2Fdp%2FB089J9QYM8&device_id=%%ADVERTISING_IDENTIFIER_PLAIN%%&vast_version=2&aid=551574&ad_duration=30&device_os=Fire%20OS&device_osv=Fire%20OS%207&dnt=%%ADVERTISING_IDENTIFIER_IS_LAT%%&gdpr=0&gdpr_consent=&video_title=%%VIDEO_TITLE%%&video_id=%%VIDEO_ID%%&video_duration=%%VIDEO_DURATION_SEC%%&us_privacy=1YNN&correlator=1597938893519
        at com.android.okhttp.Request.uri(Request.java:64)
        at com.android.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:617)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:196)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:364)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:218)
        at com.amazon.android.utils.NetworkUtils.getDataLocatedAtUrl(NetworkUtils.java:66)
        at com.amazon.android.ads.vast.processor.AdTagProcessor.process(AdTagProcessor.java:91)
        at com.amazon.android.ads.vast.VASTAdsPlayer$2.run(VASTAdsPlayer.java:578)
        at java.lang.Thread.run(Thread.java:818)
E/VASTAdsPlayer: vast error:3

Any suggested workarounds?

**Comment by ba370921** [comment]
？？？

**Comment by ba370921** [comment]
it is ok ？ now

**Comment by ba370921** [comment]
Can you tell me how to solve it
？3q
