### ISSUE TITLE
Crashes with touch screen

### ISSUE THREAD

**Issue by DerekWongMI** [amzn/fire-app-builder#68]
The build works fine with Fire TV. But since it's also listed in the amazon app store for a kindle 7, i figured I give it a try. My version of the fire app builder crashes when you - when the video is playing, tap anywhere on the screen, navigation button, would crash the app and make it restart.  Then I decided to adb the original unaltered version of fire app builder to the kindle, same result.

Anyway to correct this?

This is the logcat of the original fire app builder adb to the kindle 7. 

11-21 23:32:11.549 14143-14143/com.fireappbuilder.android.calypso D/PlaybackOverlayFragment: onInterceptInputEvent hidden true MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=510.50146, y[0]=468.21964, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=24453430, downTime=24453430, deviceId=3, source=0x1002 }
11-21 23:32:11.552 14143-14143/com.fireappbuilder.android.calypso E/InputEventReceiver: Exception dispatching input event.
11-21 23:32:11.552 14143-14143/com.fireappbuilder.android.calypso E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-21 23:32:11.554 14143-14143/com.fireappbuilder.android.calypso E/MessageQueue-JNI: java.lang.ClassCastException: android.view.MotionEvent cannot be cast to android.view.KeyEvent
                                                                                          at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment.onInterceptInputEvent(TenFootPlaybackOverlayFragment.java:535)
                                                                                          at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment.access$800(TenFootPlaybackOverlayFragment.java:71)
                                                                                          at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment$3.onInterceptTouchEvent(TenFootPlaybackOverlayFragment.java:226)
                                                                                          at android.support.v17.leanback.widget.BaseGridView.dispatchTouchEvent(BaseGridView.java:776)
                                                                                          at android.support.v17.leanback.widget.VerticalGridView.dispatchTouchEvent(VerticalGridView.java:40)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2413)
                                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1748)
                                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2758)
                                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2374)
                                                                                          at android.view.View.dispatchPointerEvent(View.java:8939)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4191)
                                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4045)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
                                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
                                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
                                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
                                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
                                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5883)
                                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5850)
                                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
                                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                          at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                                          at android.os.Looper.loop(Looper.java:122)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5491)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteIni
11-21 23:32:11.554 14143-14143/com.fireappbuilder.android.calypso D/AndroidRuntime: Shutting down VM
11-21 23:32:11.555 14143-14143/com.fireappbuilder.android.calypso E/ModularApplication: Uncaught Exception in thread Thread[main,5,main]
                                                                                        java.lang.ClassCastException: android.view.MotionEvent cannot be cast to android.view.KeyEvent
                                                                                            at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment.onInterceptInputEvent(TenFootPlaybackOverlayFragment.java:535)
                                                                                            at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment.access$800(TenFootPlaybackOverlayFragment.java:71)
                                                                                            at android.support.v17.leanback.app.TenFootPlaybackOverlayFragment$3.onInterceptTouchEvent(TenFootPlaybackOverlayFragment.java:226)
                                                                                            at android.support.v17.leanback.widget.BaseGridView.dispatchTouchEvent(BaseGridView.java:776)
                                                                                            at android.support.v17.leanback.widget.VerticalGridView.dispatchTouchEvent(VerticalGridView.java:40)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2062)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2413)
                                                                                            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1748)
                                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2758)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2374)
                                                                                            at android.view.View.dispatchPointerEvent(View.java:8939)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4191)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4045)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
                                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
                                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5883)
                                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5850)
                                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
                                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                            at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                                            at android.os.Looper.loop(Looper.java:122)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5491)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        	at com.android.inter
11-21 23:32:11.559 14143-14143/com.fireappbuilder.android.calypso E/ModularApplication: This is crash number 1

**Comment by Mariuxtheone** [comment]
FAB is designed for TV devices and not handheld devices. Recommendation is to remove handheld devices from the Amazon Appstore developer console dashboard if automatically indicated as compatible.
