### ISSUE TITLE
fire-app-builder crashes on Fire TV stick 4k(2nd gen)

### ISSUE THREAD

**Issue by jmhunter240** [amzn/fire-app-builder#88]
I am trying to port my fire-app-builder based application to Fire TV Stick 4k(2nd gen). The app crashes and returns to the main screen of the app. I also downloaded the base fire-app-builder from github and did not modify any code except to change the app name. When I installed it on the Fire TV stick 4k(2nd gen) the app crashes and goes back to the splash screen. Other applications I have built using fire-app-builder as the base behave similarly on the 4k 2nd gen stick. Please note the same apps work with no issues on previous versions of fire TV stick 4k.

Looking in the logs it is throwing this error. Please advise.

2024-06-09 19:37:43.816 24293-24393 AndroidRuntime          com...ilder.android.nnn  E  FATAL EXCEPTION: Thread-3
                                                                                                    Process: com.fireappbuilder.android.nnn, PID: 24293
                                                                                                    java.lang.IllegalAccessError: Method 'void java.lang.System.arraycopy(byte[], int, byte[], int, int)' is inaccessible to class 'com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource' (declaration of 'com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource' appears in /data/app/~~A9jMmUOSymyg4_fc3NwTMg==/com.fireappbuilder.android.nnn-vcAYKJSH_AIHb0OuO8cbiw==/base.apk)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource.read(DefaultSniffSource.java:217)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:130)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:110)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:120)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:95)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:65)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:150)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSnifferExtractorBased.sniff(MimeSnifferExtractorBased.java:105)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSniffer.getMimeType(MimeSniffer.java:79)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSniffRunnable.run(MimeSniffRunnable.java:27)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2024-06-09 19:37:43.820 24293-24393 ModularApplication      com...ilder.android.nnn  E  Uncaught Exception in thread Thread[Thread-3,5,main]
                                                                                                    java.lang.IllegalAccessError: Method 'void java.lang.System.arraycopy(byte[], int, byte[], int, int)' is inaccessible to class 'com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource' (declaration of 'com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource' appears in /data/app/~~A9jMmUOSymyg4_fc3NwTMg==/com.fireappbuilder.android.nnn-vcAYKJSH_AIHb0OuO8cbiw==/base.apk)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.DefaultSniffSource.read(DefaultSniffSource.java:217)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:240)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:130)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:110)
                                                                                                    	at com.google.android.exoplayer.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:120)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:95)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:65)
                                                                                                    	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:150)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSnifferExtractorBased.sniff(MimeSnifferExtractorBased.java:105)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSniffer.getMimeType(MimeSniffer.java:79)
                                                                                                    	at com.amazon.mediaplayer.MimeSniffer.MimeSniffRunnable.run(MimeSniffRunnable.java:27)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

**Comment by mbenedict26** [comment]
Have you, by chance, solved this issue? I got a 2nd Gen and I'm now running in to the exact same issue.

**Comment by dorsamet** [comment]
I have the same issue. Can anyone from the team help out?

**Comment by dorsamet** [comment]
There seems to be a connection to the new version which is  FireOS version 8.1.1.6. 
I tried checking if it was an SSL issue, or otherwise, and tested on other devices (Android TV + emulator) and it seems to work.
I think this may be OS specific, and we need to update the exoplayer library..
